// Generated from portfolio.json by scripts/generate-portfolio-contract.mjs.
// Do not edit this file directly.
import type { PortfolioConfig } from "./schema.generated";

const portfolio = {
  "$schema": "./portfolio.schema.json",
  "site": {
    "identity": {
      "name": "Your Name",
      "firstName": "You",
      "initials": "YN",
      "role": "Product Designer",
      "company": "Example Studio",
      "locale": "en-US"
    },
    "origin": "https://example.com",
    "themeColor": "#ffffff",
    "copyrightYear": 2026,
    "contact": {
      "email": "hello@example.com",
      "helloSubject": "Hello!",
      "hiSubject": "Hi"
    },
    "socialLinks": [
      {
        "label": "Twitter",
        "icon": "twitter",
        "href": "https://example.com/#twitter",
        "brand": "#000000"
      },
      {
        "label": "LinkedIn",
        "icon": "linkedin",
        "href": "https://example.com/#linkedin",
        "brand": "#0A66C2"
      },
      {
        "label": "Instagram",
        "icon": "instagram",
        "href": "https://example.com/#instagram",
        "brand": "#E1306C"
      },
      {
        "label": "Email",
        "icon": "email",
        "href": "mailto:hello@example.com",
        "brand": "#EA4335"
      }
    ],
    "navigation": [
      {
        "label": "About",
        "href": "#about",
        "sectionId": "about"
      },
      {
        "label": "Work",
        "href": "#work",
        "sectionId": "work"
      },
      {
        "label": "Photography",
        "href": "#photography",
        "sectionId": "photography"
      },
      {
        "label": "Blogs",
        "href": "/blogs",
        "sectionId": null,
        "newTab": true,
        "demoOnly": true
      }
    ],
    "location": {
      "city": "San Francisco",
      "country": "United States",
      "timeZone": "America/Los_Angeles",
      "timeZoneLabel": "PT",
      "latitude": 37.7749,
      "longitude": -122.4194
    },
    "resume": {
      "image": "/assets/demo/example-resume.svg",
      "pdf": "/assets/demo/example-resume.pdf",
      "downloadName": "Example-Resume.pdf"
    },
    "assets": {
      "socialPreview": "/ogportfolio-logo.webp",
      "icon": "/favicon.ico",
      "appleTouchIcon": "/apple-touch-icon.png"
    }
  },
  "features": {
    "weather": true,
    "about": true,
    "work": true,
    "photography": true,
    "resume": true,
    "demoRoutes": true
  },
  "hero": {
    "greetings": [
      "Hello",
      "Namaste",
      "Bonjour",
      "Hola",
      "Ciao",
      "Olá",
      "Hallo",
      "Guten Tag",
      "Salaam",
      "Konnichiwa"
    ],
    "portraits": [
      "/assets/demo/photo-01.svg",
      "/assets/demo/photo-02.svg",
      "/assets/demo/photo-03.svg",
      "/assets/demo/photo-04.svg"
    ],
    "roleLine": [
      {
        "text": "Product Designer at "
      },
      {
        "brand": {
          "name": "Example Studio",
          "icon": "/assets/demo/logo-placeholder.svg"
        }
      }
    ],
    "summary": [
      {
        "text": "Example portfolio based in San Francisco, demonstrating product storytelling with "
      },
      {
        "brand": {
          "name": "District by Zomato",
          "icon": "/assets/district-icon-fad26ad7.png"
        }
      },
      {
        "text": " and side projects such as "
      },
      {
        "brand": {
          "name": "Brink",
          "icon": "/brink/logo.png"
        }
      },
      {
        "text": ", a podcast player."
      }
    ]
  },
  "about": {
    "timeline": [
      {
        "year": "2020",
        "title": "Started design",
        "desc": "Example milestone — replace this with the moment your own story begins.",
        "current": false
      },
      {
        "year": "2022",
        "title": "Built first product",
        "desc": "Example milestone for a project, role, or turning point in your work.",
        "current": false
      },
      {
        "year": "2024",
        "title": "Expanded the craft",
        "desc": "Example milestone showing how your skills or responsibilities evolved.",
        "current": false
      },
      {
        "year": "2026",
        "title": "Current chapter",
        "desc": "Replace this with what you are focused on today.",
        "current": true
      }
    ],
    "story": [
      [
        {
          "tone": "muted",
          "text": "This is example copy for the reusable FolioWeave template. "
        },
        {
          "tone": "strong",
          "text": "Use this opening paragraph to explain what first drew you toward design and making things. "
        },
        {
          "tone": "muted",
          "text": "Keep the story simple and specific rather than dramatic. "
        },
        {
          "tone": "strong",
          "text": "Call out the idea that eventually became your focus over time: "
        },
        {
          "tone": "highlight",
          "text": "product design"
        },
        {
          "tone": "strong",
          "text": "."
        }
      ],
      [
        {
          "tone": "muted",
          "text": "Before the work itself, talk about the interests that shaped your eye for detail. Maybe that was photography, hardware, illustration, music, or something completely different. "
        },
        {
          "tone": "strong",
          "text": "The point is not to manufacture an origin story; it is to show the thread between what you notice, what you enjoy making, and how that perspective shows up in your work."
        }
      ],
      [
        {
          "tone": "muted",
          "text": "Use the final paragraph to connect those interests to the way you work now. "
        },
        {
          "tone": "strong",
          "text": "Explain what you like solving, how you balance craft with constraints, and what kind of products or experiences you want to keep building."
        }
      ]
    ],
    "galleryImages": [
      {
        "src": "/assets/demo/photo-02.svg",
        "alt": "Photo placeholder 1"
      },
      {
        "src": "/assets/demo/photo-01.svg",
        "alt": "Photo placeholder 2"
      },
      {
        "src": "/assets/demo/photo-03.svg",
        "alt": "Photo placeholder 3"
      },
      {
        "src": "/assets/demo/photo-wide.svg",
        "alt": "Photo placeholder 4"
      }
    ]
  },
  "projects": [
    {
      "id": "district",
      "enabled": true,
      "name": "District by Zomato",
      "date": "Jan 2025 — Apr 2026",
      "description": "I design for the Movies vertical at District by Zomato, facilitating over 75 million ticket sales. My focus is on creating scalable, easy-to-use flows that balance business goals with a great user experience.",
      "icon": "/assets/district-icon-fad26ad7.png",
      "badge": {
        "text": "Best App of 2025 - Google Play",
        "tone": "gold"
      },
      "actions": [
        {
          "label": "View Case Study",
          "href": "/district",
          "icon": "arrow"
        }
      ],
      "story": {
        "title": "Story time",
        "image": "/assets/demo/project-placeholder.svg",
        "imageAlt": "Project image placeholder",
        "body": "A designer shared a project note with a product leader, and they replied! That conversation became an unexpected opportunity to keep working on the product, which later turned into a longer collaboration. Sometimes, reaching out with a thoughtful message can open doors you never expected."
      },
      "mobileTreatment": "standard",
      "media": {
        "kind": "image",
        "image": {
          "src": "/media/5c0589_7a30aeef55604850b2cb9994e87dd196~mv2.webp",
          "mobile": "/media/5c0589_0a1ded0ebf574f41a427c109a3ab6ca8~mv2.webp",
          "alt": "District by Zomato"
        }
      }
    },
    {
      "id": "brink",
      "enabled": true,
      "name": "Brink",
      "date": "Feb 2026 — Present",
      "description": "A podcast player and news app I designed and built solo — discovery, playback, and headlines all in one place. Features include trending podcast recommendations, timestamped bookmarks, and a walking mode. Built with a modern Liquid Glass design for iOS.",
      "icon": "/brink/logo.png",
      "badge": {
        "text": "Featured on 9to5Mac",
        "tone": "gold",
        "href": "https://9to5mac.com/2026/06/20/indie-app-spotlight-brink-brings-a-feature-rich-experience-to-iphone-podcast-listening/"
      },
      "actions": [
        {
          "label": "View in App Store",
          "href": "https://apps.apple.com/in/app/brink-podcasts-and-news/id6760338948",
          "icon": "arrow"
        }
      ],
      "mobileTreatment": "featured",
      "media": {
        "kind": "image",
        "image": {
          "src": "/media/brink-work-desktop.jpg",
          "mobile": "/media/brink-work-mobile.jpg",
          "alt": "Brink podcast discovery screens"
        }
      }
    },
    {
      "id": "clipt",
      "enabled": true,
      "name": "Clipt",
      "date": "Jan 2026",
      "description": "I designed and built Clipt to solve a personal pain point: the lack of a native, synced clipboard history on iOS. Built with SwiftUI and SwiftData, it features a custom keyboard extension for instant access to your clips, seamless iCloud synchronization, and a polished, native feel that fits perfectly into the Apple ecosystem.",
      "icon": "/media/5c0589_4015772c87e6491eb8881e3764409267~mv2.webp",
      "badge": {
        "text": "#1 Paid App in India - App Store",
        "tone": "blue"
      },
      "actions": [
        {
          "label": "View Product",
          "href": "/clipt",
          "icon": "arrow"
        },
        {
          "label": "Read the Story",
          "href": "/blogs/clipt",
          "icon": "book",
          "tone": "accent"
        }
      ],
      "mobileTreatment": "featured",
      "media": {
        "kind": "image",
        "image": {
          "src": "/media/5c0589_f2650350f5424f63986ad52a542e14b7~mv2.webp",
          "mobile": "/media/5c0589_4397853e33df48cbae9a1f8b56d8417f~mv2.webp",
          "alt": "Clipt - Clipboard History"
        }
      }
    },
    {
      "id": "habee",
      "enabled": true,
      "name": "Habee",
      "date": "Jan 2026",
      "description": "A minimal habit tracker built with SwiftUI — simple, focused, and designed to help you build better routines without overwhelming you with features.",
      "actions": [
        {
          "label": "View in App Store",
          "href": "https://apps.apple.com/in/app/habee-habit-tracker/id6757213438",
          "icon": "arrow"
        }
      ],
      "mobileTreatment": "featured",
      "media": {
        "kind": "image",
        "image": {
          "src": "/media/5c0589_8035037444ae49d2bb661f3a5c001786~mv2.webp",
          "mobile": "/media/5c0589_e510a0a265744c628a6f5be98d165764~mv2.webp",
          "alt": "Habee - Habit Tracker"
        }
      }
    },
    {
      "id": "og-walls",
      "enabled": true,
      "name": "OG Walls",
      "date": "Aug 2025",
      "description": "OG Walls is an Android app I built that offers a free collection of high-quality wallpapers. All the photos in the app are original and were captured by me. The app is a showcase of my personal photography portfolio, giving users a unique and refreshing alternative to generic stock photos.",
      "actions": [
        {
          "label": "View in Play Store",
          "href": "https://play.google.com/store/apps/details?id=com.ogwalls.app",
          "icon": "arrow"
        }
      ],
      "mobileTreatment": "standard",
      "media": {
        "kind": "image",
        "image": {
          "src": "/media/5c0589_b6de3c913beb49b386b9792f9f4ade48~mv2.webp",
          "mobile": "/media/5c0589_4ea5c5899e764cfc9e88a6e43827f725~mv2.webp",
          "alt": "OG Walls"
        }
      }
    },
    {
      "id": "notchshelf",
      "enabled": true,
      "name": "NotchShelf",
      "date": "Jan 2026",
      "description": "I turned the MacBook Notch into a functional workspace! NotchShelf transforms that \"dead space\" into a dynamic utility belt with a Quick Shelf for files, a Screenshot Magnet, and a Quick Mirror. Built with SwiftUI as my first macOS app, it reached #1 Paid App in India on the Mac App Store.",
      "icon": "/notchshelf-logo.webp",
      "badge": {
        "text": "#1 Paid App in India - App Store",
        "tone": "blue",
        "previewImage": "/media/5c0589_43f2662bccd344f6b5d833dc0ec16ea0~mv2.webp",
        "previewMaxWidth": 300
      },
      "actions": [
        {
          "label": "View in App Store",
          "href": "https://apps.apple.com/in/app/notchshelf-folders-in-notch/id6757535797?mt=12",
          "icon": "arrow"
        }
      ],
      "mobileTreatment": "standard",
      "media": {
        "kind": "carousel",
        "images": [
          {
            "src": "/media/5c0589_6ac998ac67574efe8de1ce8e005273f0~mv2.webp",
            "alt": "NotchShelf screenshot 1"
          },
          {
            "src": "/media/5c0589_ea6630f53b474533bae973ba423892b5~mv2.webp",
            "alt": "NotchShelf screenshot 2"
          },
          {
            "src": "/media/5c0589_6cdb4dc09a8c4b0c951116889a6e4856~mv2.webp",
            "alt": "NotchShelf screenshot 3"
          },
          {
            "src": "/media/5c0589_543c0982737648b7ba00cf8f05a23000~mv2.webp",
            "alt": "NotchShelf screenshot 4"
          },
          {
            "src": "/media/5c0589_4e9f8672707a43daa7b64d6d2cfe31b9~mv2.webp",
            "alt": "NotchShelf screenshot 5"
          }
        ]
      }
    }
  ],
  "photography": {
    "intro": "And hey, I love photography.",
    "images": [
      {
        "src": "/media/5c0589_73583c6e0d78476c97acc3a7ea179510~mv2.webp",
        "alt": "Portfolio photograph 1"
      },
      {
        "src": "/media/5c0589_efb61fd0050843a4b8cdec62493de85e~mv2.webp",
        "alt": "Portfolio photograph 2"
      },
      {
        "src": "/media/5c0589_e5a8942da56147d49a06a929fc312864~mv2.webp",
        "alt": "Portfolio photograph 3"
      },
      {
        "src": "/media/5c0589_7ab49e27a66b414f87aac76285523413~mv2.webp",
        "alt": "Portfolio photograph 4"
      },
      {
        "src": "/media/5c0589_34bde73293b34a3e820a380e8566259c~mv2.webp",
        "alt": "Portfolio photograph 5"
      },
      {
        "src": "/media/5c0589_b20ecdaceb33447d9dd3088dabcd24a6~mv2.webp",
        "alt": "Portfolio photograph 6"
      },
      {
        "src": "/media/5c0589_993e246b6ef145f7ae710024bcc04b61~mv2.webp",
        "alt": "Portfolio photograph 7"
      },
      {
        "src": "/media/5c0589_2114ae1b4c2a4844a205efd5c32caf39~mv2.webp",
        "alt": "Portfolio photograph 8"
      },
      {
        "src": "/media/5c0589_9176cd08731745888749fd42c230945c~mv2.webp",
        "alt": "Portfolio photograph 9"
      },
      {
        "src": "/media/5c0589_6d20c3f02c4141b797c006682f422e28~mv2.webp",
        "alt": "Portfolio photograph 10"
      },
      {
        "src": "/media/5c0589_c2e0392b0d4e4d3cad2515d76472fa6c~mv2.webp",
        "alt": "Portfolio photograph 11"
      },
      {
        "src": "/media/5c0589_37bc8f979b374232882320fb4f341eb2~mv2.webp",
        "alt": "Portfolio photograph 12"
      },
      {
        "src": "/media/5c0589_c551be0fd9ce4bfd8a179abe76b1ae83~mv2.webp",
        "alt": "Portfolio photograph 13"
      },
      {
        "src": "/media/5c0589_bc243d74532e485db6c65812ab8b622b~mv2.webp",
        "alt": "Portfolio photograph 14"
      },
      {
        "src": "/media/5c0589_aa87bfa7f0d74a45933715685ed66614~mv2.webp",
        "alt": "Portfolio photograph 15"
      },
      {
        "src": "/media/5c0589_4f0120a34ba646dc9d951d108953e15e~mv2.webp",
        "alt": "Portfolio photograph 16"
      },
      {
        "src": "/media/5c0589_bafbecbb93a046538a666329f8b3a4b0~mv2.webp",
        "alt": "Portfolio photograph 17"
      },
      {
        "src": "/media/5c0589_fdc7d062ceaa435582bfe4e4d4a48d06~mv2.webp",
        "alt": "Portfolio photograph 18"
      }
    ]
  },
  "footerBook": {
    "title": "PHIL'S-OPHY",
    "quote": "When life gives you lemonade, make lemons. Life will be all like 'Whaaat?!'",
    "author": "Phil Dunphy"
  },
  "seo": {
    "description": "FolioWeave example portfolio template demonstrating product design work, case studies, photography, writing, and interactive portfolio components.",
    "keywords": [
      "portfolio template",
      "product design portfolio",
      "UX design portfolio",
      "UI design portfolio",
      "developer portfolio",
      "case study portfolio",
      "design systems",
      "interaction design",
      "responsive design",
      "Next.js portfolio"
    ],
    "knowsAbout": [
      "Product Design",
      "User Experience Design",
      "User Interface Design",
      "Digital Product Design",
      "Design Systems",
      "Interaction Design",
      "Web Design"
    ],
    "caseStudiesDescription": "Example product-design case studies demonstrating long-form project storytelling, responsive media, metrics, and portfolio navigation."
  },
  "blog": {
    "title": "Blogs",
    "heading": "Blogs",
    "description": "Thoughts on design, code, and building products.",
    "intro": [
      {
        "text": "Thoughts on "
      },
      {
        "text": "design engineering",
        "tone": "highlight"
      },
      {
        "text": ", "
      },
      {
        "text": "product philosophy",
        "tone": "highlight"
      },
      {
        "text": ", and the "
      },
      {
        "text": "obsession with detail",
        "tone": "highlight"
      },
      {
        "text": "."
      }
    ]
  },
  "interlude": {
    "title": "Sometimes, I zoom out.",
    "description": "The best decisions rarely come from staring harder at the screen. They come from stepping back — seeing how one small choice ripples through a whole system, and remembering the person on the other end of it.",
    "returnTitle": "Then I bring it back down.",
    "handwrittenTitle": "And keep it simple.",
    "returnDescription": "Good solutions don't ask for attention. They just work—quietly and effectively.",
    "image": "/media/5c0589_8d8640a87e5a4209b0cb5e6ba984ddc8~mv2.webp"
  }
} satisfies PortfolioConfig;

export default portfolio;
