// Generated by content:build. Do not edit.
export const mediaManifest: Record<string, { width: number; height: number }> = {
  "/apple-touch-icon.png": {
    "width": 180,
    "height": 180
  },
  "/assets/cred-icon-6de258e2.png": {
    "width": 512,
    "height": 512
  },
  "/assets/district-icon-fad26ad7.png": {
    "width": 1014,
    "height": 1024
  },
  "/brink/logo.png": {
    "width": 1024,
    "height": 1024
  },
  "/gowtham-oleti-resume.jpg": {
    "width": 1489,
    "height": 2105
  },
  "/media/5c0589_0a1ded0ebf574f41a427c109a3ab6ca8~mv2.webp": {
    "width": 2000,
    "height": 1744
  },
  "/media/5c0589_2114ae1b4c2a4844a205efd5c32caf39~mv2.webp": {
    "width": 914,
    "height": 1626
  },
  "/media/5c0589_276c5292e97441c89ba57bded4b74fea~mv2.webp": {
    "width": 2000,
    "height": 1125
  },
  "/media/5c0589_2b7dce66597e49978dc260479073bd5d~mv2.webp": {
    "width": 2000,
    "height": 547
  },
  "/media/5c0589_34bde73293b34a3e820a380e8566259c~mv2.webp": {
    "width": 1125,
    "height": 2000
  },
  "/media/5c0589_37bc8f979b374232882320fb4f341eb2~mv2.webp": {
    "width": 914,
    "height": 1626
  },
  "/media/5c0589_4015772c87e6491eb8881e3764409267~mv2.webp": {
    "width": 2000,
    "height": 2000
  },
  "/media/5c0589_42a00ff8590c4ff5b1cf8496183b08b8~mv2.webp": {
    "width": 2000,
    "height": 1243
  },
  "/media/5c0589_4397853e33df48cbae9a1f8b56d8417f~mv2.webp": {
    "width": 2000,
    "height": 1744
  },
  "/media/5c0589_43f2662bccd344f6b5d833dc0ec16ea0~mv2.webp": {
    "width": 896,
    "height": 1036
  },
  "/media/5c0589_4e9f8672707a43daa7b64d6d2cfe31b9~mv2.webp": {
    "width": 2000,
    "height": 1250
  },
  "/media/5c0589_4ea5c5899e764cfc9e88a6e43827f725~mv2.webp": {
    "width": 2000,
    "height": 1744
  },
  "/media/5c0589_4f0120a34ba646dc9d951d108953e15e~mv2.webp": {
    "width": 964,
    "height": 1714
  },
  "/media/5c0589_50f17c427f3d47a890204bec7d6b5b2a~mv2.webp": {
    "width": 1500,
    "height": 2000
  },
  "/media/5c0589_543c0982737648b7ba00cf8f05a23000~mv2.webp": {
    "width": 2000,
    "height": 1250
  },
  "/media/5c0589_6ac998ac67574efe8de1ce8e005273f0~mv2.webp": {
    "width": 2000,
    "height": 1250
  },
  "/media/5c0589_6cdb4dc09a8c4b0c951116889a6e4856~mv2.webp": {
    "width": 2000,
    "height": 1250
  },
  "/media/5c0589_6d20c3f02c4141b797c006682f422e28~mv2.webp": {
    "width": 918,
    "height": 1626
  },
  "/media/5c0589_73583c6e0d78476c97acc3a7ea179510~mv2.webp": {
    "width": 1264,
    "height": 2000
  },
  "/media/5c0589_77fafd7e8f0545bca52b40171db03280~mv2.webp": {
    "width": 1104,
    "height": 1626
  },
  "/media/5c0589_7a30aeef55604850b2cb9994e87dd196~mv2.webp": {
    "width": 2000,
    "height": 1206
  },
  "/media/5c0589_7ab49e27a66b414f87aac76285523413~mv2.webp": {
    "width": 1125,
    "height": 2000
  },
  "/media/5c0589_8035037444ae49d2bb661f3a5c001786~mv2.webp": {
    "width": 2000,
    "height": 1206
  },
  "/media/5c0589_8181afcd1a6041a2bd8abbca5dea28c2~mv2.webp": {
    "width": 1220,
    "height": 1626
  },
  "/media/5c0589_8d8640a87e5a4209b0cb5e6ba984ddc8~mv2.webp": {
    "width": 1920,
    "height": 765
  },
  "/media/5c0589_9176cd08731745888749fd42c230945c~mv2.webp": {
    "width": 914,
    "height": 1626
  },
  "/media/5c0589_993e246b6ef145f7ae710024bcc04b61~mv2.webp": {
    "width": 720,
    "height": 1260
  },
  "/media/5c0589_aa87bfa7f0d74a45933715685ed66614~mv2.webp": {
    "width": 1125,
    "height": 2000
  },
  "/media/5c0589_b20ecdaceb33447d9dd3088dabcd24a6~mv2.webp": {
    "width": 1125,
    "height": 2000
  },
  "/media/5c0589_b6de3c913beb49b386b9792f9f4ade48~mv2.webp": {
    "width": 2000,
    "height": 1206
  },
  "/media/5c0589_bafbecbb93a046538a666329f8b3a4b0~mv2.webp": {
    "width": 1125,
    "height": 2000
  },
  "/media/5c0589_bc243d74532e485db6c65812ab8b622b~mv2.webp": {
    "width": 964,
    "height": 1714
  },
  "/media/5c0589_c2e0392b0d4e4d3cad2515d76472fa6c~mv2.webp": {
    "width": 978,
    "height": 1626
  },
  "/media/5c0589_c551be0fd9ce4bfd8a179abe76b1ae83~mv2.webp": {
    "width": 1008,
    "height": 1714
  },
  "/media/5c0589_e35aa4884b1a47d388a577b03cb7b4ef~mv2.webp": {
    "width": 1500,
    "height": 2000
  },
  "/media/5c0589_e510a0a265744c628a6f5be98d165764~mv2.webp": {
    "width": 2000,
    "height": 1744
  },
  "/media/5c0589_e5a8942da56147d49a06a929fc312864~mv2.webp": {
    "width": 900,
    "height": 1600
  },
  "/media/5c0589_ea6630f53b474533bae973ba423892b5~mv2.webp": {
    "width": 2000,
    "height": 1250
  },
  "/media/5c0589_efb61fd0050843a4b8cdec62493de85e~mv2.webp": {
    "width": 1125,
    "height": 2000
  },
  "/media/5c0589_f2650350f5424f63986ad52a542e14b7~mv2.webp": {
    "width": 2000,
    "height": 1206
  },
  "/media/5c0589_fdc7d062ceaa435582bfe4e4d4a48d06~mv2.webp": {
    "width": 1078,
    "height": 1916
  },
  "/media/5c0589_ffd5758e00f9438abc3f9fe91512d589~mv2.webp": {
    "width": 1498,
    "height": 2000
  },
  "/media/brink-work-desktop.jpg": {
    "width": 2400,
    "height": 1447
  },
  "/media/brink-work-mobile.jpg": {
    "width": 1800,
    "height": 1569
  },
  "/notchshelf-logo.webp": {
    "width": 1024,
    "height": 1024
  },
  "/ogportfolio-logo.webp": {
    "width": 77,
    "height": 85
  }
};
