// Generated by content:build. Do not edit.
export const mediaManifest: Record<string, { width: number; height: number }> = {
  "/media/5c0589_8d8640a87e5a4209b0cb5e6ba984ddc8~mv2.webp": {
    "width": 1920,
    "height": 765
  },
  "/portfolio/photography/about-01.jpg": {
    "width": 1536,
    "height": 2048
  },
  "/portfolio/photography/about-02.jpg": {
    "width": 1280,
    "height": 1706
  },
  "/portfolio/photography/about-03.jpg": {
    "width": 2048,
    "height": 1536
  },
  "/portfolio/photography/about-04.jpg": {
    "width": 1280,
    "height": 1707
  },
  "/portfolio/photography/photo-01.jpg": {
    "width": 2048,
    "height": 1536
  },
  "/portfolio/photography/photo-02.jpg": {
    "width": 2048,
    "height": 1536
  },
  "/portfolio/photography/photo-03.jpg": {
    "width": 1706,
    "height": 1280
  },
  "/portfolio/photography/photo-04.webp": {
    "width": 2400,
    "height": 1800
  },
  "/portfolio/photography/photo-05.webp": {
    "width": 2400,
    "height": 1800
  },
  "/portfolio/photography/photo-06.webp": {
    "width": 2400,
    "height": 1800
  },
  "/portfolio/photography/photo-07.webp": {
    "width": 1350,
    "height": 2400
  },
  "/portfolio/photography/photo-08.jpg": {
    "width": 2048,
    "height": 1536
  },
  "/portfolio/photography/photo-09.jpg": {
    "width": 2048,
    "height": 1536
  },
  "/portfolio/photography/photo-10.jpg": {
    "width": 2048,
    "height": 1536
  },
  "/portfolio/photography/photo-11.jpg": {
    "width": 2048,
    "height": 1536
  },
  "/portfolio/photography/photo-12.jpg": {
    "width": 1440,
    "height": 2560
  },
  "/portfolio/photography/photo-13.jpg": {
    "width": 2560,
    "height": 1920
  },
  "/portfolio/photography/photo-14.jpg": {
    "width": 2560,
    "height": 1920
  },
  "/portfolio/photography/photo-15.jpg": {
    "width": 2560,
    "height": 1920
  },
  "/portfolio/photography/photo-16.jpg": {
    "width": 1920,
    "height": 1280
  },
  "/portfolio/photography/photo-17.jpg": {
    "width": 2560,
    "height": 1920
  },
  "/portfolio/photography/photo-18.jpg": {
    "width": 2560,
    "height": 1440
  },
  "/portfolio/photography/photo-20.jpg": {
    "width": 1536,
    "height": 2048
  },
  "/portfolio/profile/apple-touch-icon.png": {
    "width": 180,
    "height": 180
  },
  "/portfolio/profile/favicon.png": {
    "width": 96,
    "height": 96
  },
  "/portfolio/profile/hero-portrait-01.png": {
    "width": 675,
    "height": 900
  },
  "/portfolio/profile/social-preview.png": {
    "width": 675,
    "height": 900
  },
  "/portfolio/projects/crew/crew-main-mobile.png": {
    "width": 2000,
    "height": 1744
  },
  "/portfolio/projects/crew/crew-main.png": {
    "width": 2000,
    "height": 1206
  },
  "/portfolio/projects/crew/crew-play-store.png": {
    "width": 2400,
    "height": 657
  },
  "/portfolio/projects/crew/icon.png": {
    "width": 512,
    "height": 512
  },
  "/portfolio/projects/devmate/devmate-main.png": {
    "width": 2000,
    "height": 1206
  },
  "/portfolio/projects/devmate/icon.png": {
    "width": 128,
    "height": 128
  },
  "/portfolio/resume/liu-zhong-li-cv.png": {
    "width": 1240,
    "height": 1754
  }
};
