// Generated from portfolio.schema.json by scripts/generate-portfolio-contract.mjs.
// Do not edit this file directly.

/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "hexColor".
 */
export type HexColor = string;
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "localImage".
 */
export type LocalImage = LocalPath;
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "localPath".
 */
export type LocalPath = string;
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "localPdf".
 */
export type LocalPdf = LocalPath;
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "richTextSegment".
 */
export type RichTextSegment =
  | {
      text: string;
    }
  | {
      brand: {
        name: string;
        icon: LocalImage;
      };
    };
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "projectMedia".
 */
export type ProjectMedia =
  | {
      kind: "image";
      image: ProjectImage;
    }
  | {
      kind: "carousel";
      /**
       * @minItems 1
       */
      images: [ProjectCarouselImage, ...ProjectCarouselImage[]];
    };
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "localIcon".
 */
export type LocalIcon = LocalPath;

/**
 * Single-source content and personalization configuration for FolioWeave.
 */
export interface PortfolioConfig {
  $schema?: string;
  site: {
    /**
     * Public identity used across the hero, metadata, structured data, and contact surfaces.
     */
    identity: {
      name: string;
      firstName: string;
      initials: string;
      role: string;
      /**
       * Optional company or studio name. Leave empty for independent/freelance portfolios.
       */
      company: string;
      /**
       * BCP 47 locale such as en-US, en-GB, it-IT, or zh-CN.
       */
      locale: string;
    };
    /**
     * Canonical production URL, for example https://example.com.
     */
    origin: string;
    themeColor: HexColor;
    copyrightYear: number;
    contact: {
      email: string;
      helloSubject: string;
      hiSubject: string;
    };
    /**
     * Footer/profile social links. Remove entries you do not use.
     */
    socialLinks: {
      label: string;
      icon: "twitter" | "linkedin" | "instagram" | "github" | "email" | "website";
      href: string;
      brand: HexColor;
    }[];
    /**
     * Navigation definitions. Section links are automatically hidden when their feature is disabled.
     */
    navigation: {
      label: string;
      href: string;
      sectionId: string | null;
      newTab?: boolean;
      /**
       * Hide this navigation item when features.demoRoutes is false.
       */
      demoOnly?: boolean;
    }[];
    location: {
      city: string;
      country: string;
      timeZone: string;
      timeZoneLabel: string;
      latitude: number;
      longitude: number;
    };
    /**
     * Author resume files and download name. Referenced source files must exist even when the feature is disabled; disabled resume files are excluded from publication unless another published item references them.
     */
    resume: {
      image: LocalImage;
      pdf: LocalPdf;
      downloadName: string;
    };
    assets: {
      /**
       * Local Open Graph/social preview asset under public/. Prefer a 1200x630 PNG, JPEG, or WebP for broad crawler compatibility.
       */
      socialPreview: LocalPath;
      /**
       * Primary browser/favicon asset under public/. Clean mode uses a neutral SVG placeholder until you replace it.
       */
      icon: LocalPath;
      /**
       * Apple touch icon under public/. Prefer a 180x180 PNG before publishing.
       */
      appleTouchIcon: LocalPath;
    };
  };
  /**
   * Feature switches for optional homepage sections and bundled example routes.
   */
  features: {
    /**
     * Show weather next to local time and enable /api/weather.
     */
    weather: boolean;
    /**
     * Render the About section and its navigation entry.
     */
    about: boolean;
    /**
     * Render enabled projects and the Work navigation entry.
     */
    work: boolean;
    /**
     * Render the photography gallery and its navigation entry.
     */
    photography: boolean;
    /**
     * Enable the interactive resume printer and require configured resume files.
     */
    resume: boolean;
    /**
     * Expose bundled example detail/blog/privacy routes and the demo-only podcast API.
     */
    demoRoutes: boolean;
  };
  hero: {
    /**
     * @minItems 1
     */
    greetings: [string, ...string[]];
    /**
     * One or more local portrait images. Clicking the hero card rotates through them.
     *
     * @minItems 1
     */
    portraits: [LocalImage, ...LocalImage[]];
    /**
     * Rich inline hero role line. Segments can be plain text or a brand with icon.
     */
    roleLine: RichTextSegment[];
    /**
     * Rich inline hero summary. Segments can be plain text or a brand with icon.
     */
    summary: RichTextSegment[];
  };
  about: {
    timeline: {
      year: string;
      title: string;
      desc: string;
      /**
       * Explicit current role; independent of the calendar year.
       */
      current?: boolean;
    }[];
    story: {
      tone: "muted" | "strong" | "highlight";
      text: string;
    }[][];
    galleryImages: MediaAsset[];
  };
  /**
   * Ordered project list. Add, remove, reorder, or disable projects without editing React components.
   */
  projects: Project[];
  photography: {
    intro: string;
    images: MediaAsset[];
  };
  blog: {
    /**
     * Blog title used for metadata and as the default visible heading.
     */
    title: string;
    /**
     * Optional visible heading when the editorial heading differs from the metadata title.
     */
    heading?: string;
    description: string;
    /**
     * Optional rich intro. When omitted, description is rendered as plain text.
     */
    intro?: {
      text: string;
      tone?: "highlight";
    }[];
  };
  footerBook: {
    title: string;
    quote: string;
    author: string;
  };
  /**
   * Root metadata and structured-data content derived into Next.js SEO outputs.
   */
  seo: {
    /**
     * Primary site description used for metadata, Open Graph, Twitter, Manifest, and Person JSON-LD.
     */
    description: string;
    /**
     * Search keywords for the root portfolio page.
     */
    keywords: string[];
    /**
     * Topics included in Person structured data.
     */
    knowsAbout: string[];
    /**
     * Optional personal/site award. Remove when not applicable.
     */
    award?: string;
    caseStudiesDescription: string;
  };
  interlude: {
    title: string;
    description: string;
    returnTitle: string;
    handwrittenTitle: string;
    returnDescription: string;
    image: LocalImage;
  };
}
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "mediaAsset".
 */
export interface MediaAsset {
  src: LocalImage;
  alt: string;
}
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "project".
 */
export interface Project {
  /**
   * Stable lowercase slug used as the React key. Must be unique.
   */
  id: string;
  /**
   * Whether this project appears in the Work section.
   */
  enabled: boolean;
  /**
   * Controls only the mobile card treatment; media kind and editorial story are modeled independently.
   */
  mobileTreatment: "standard" | "featured";
  name: string;
  date: string;
  description: string;
  icon?: LocalImage;
  /**
   * Discriminated image or carousel media. Legacy image/carouselImages fields are intentionally unsupported.
   */
  media:
    | {
        kind: "image";
        image: ProjectImage;
      }
    | {
        kind: "carousel";
        /**
         * @minItems 1
         */
        images: [ProjectCarouselImage, ...ProjectCarouselImage[]];
      };
  badge?: ProjectBadge;
  /**
   * Project links such as case studies, store pages, stories, or external sites.
   */
  actions?: ProjectAction[];
  story?: ProjectStory;
}
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "projectImage".
 */
export interface ProjectImage {
  /**
   * Default project artwork used on desktop and as the mobile fallback.
   */
  src: LocalPath;
  /**
   * Optional mobile-specific override. Omit it to reuse src.
   */
  mobile?: LocalPath;
  alt: string;
}
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "projectCarouselImage".
 */
export interface ProjectCarouselImage {
  /**
   * Default carousel slide used on desktop and as the mobile fallback.
   */
  src: LocalPath;
  /**
   * Optional mobile-specific override for this same slide.
   */
  mobile?: LocalPath;
  alt: string;
}
/**
 * Optional award/press badge displayed near project metadata.
 */
export interface ProjectBadge {
  text: string;
  /**
   * Visual badge style.
   */
  tone: "gold" | "blue";
  href?: string;
  /**
   * Optional local image shown as a hover preview.
   */
  previewImage?: LocalPath;
  previewMaxWidth?: number;
}
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "projectAction".
 */
export interface ProjectAction {
  label: string;
  /**
   * Internal path beginning with / or an absolute http(s) URL.
   */
  href: string;
  icon?: "arrow" | "book";
  /**
   * Use accent for secondary/editorial links; default for normal links.
   */
  tone?: "default" | "accent";
  /**
   * Overrides link behavior. External links open in a new tab by default; internal links stay in the current tab.
   */
  newTab?: boolean;
}
/**
 * Optional editorial story block, independent from the card's media and mobile treatment.
 */
export interface ProjectStory {
  title: string;
  image: LocalImage;
  imageAlt: string;
  body: string;
}
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "projectBadge".
 */
export interface ProjectBadge1 {
  text: string;
  /**
   * Visual badge style.
   */
  tone: "gold" | "blue";
  href?: string;
  /**
   * Optional local image shown as a hover preview.
   */
  previewImage?: LocalPath;
  previewMaxWidth?: number;
}
/**
 * This interface was referenced by `PortfolioConfig`'s JSON-Schema
 * via the `definition` "projectStory".
 */
export interface ProjectStory1 {
  title: string;
  image: LocalImage;
  imageAlt: string;
  body: string;
}
