const en = {
  heading: "Comments",
  load: "Show comments",
  loading: "Loading comments…",
  retry: "Try again",
  refresh: "Refresh comments",
  unavailable: "Comments are unavailable right now. Please try again.",
  name: "Name",
  email: "Email",
  optional: "optional",
  placeholder: "Write a comment…",
  send: "Post",
  sending: "Posting…",
  login: "Sign in",
  logout: "Sign out",
  reply: "Reply",
  replyTo: "Replying to",
  cancel: "Cancel reply",
  like: "Like",
  unlike: "Unlike",
  latest: "Newest",
  oldest: "Oldest",
  hottest: "Most liked",
  sort: "Sort comments",
  empty: "No comments yet.",
  more: "Show more",
  author: "Author",
  pinned: "Pinned",
  pending: "Awaiting moderation",
  sent: "Posted.",
  review: "Your comment was submitted for moderation.",
  failed: "Could not post your comment. Your text has been kept.",
  unknown:
    "The request timed out. Refresh comments before retrying; it may have been received.",
  required: "Enter your name and a comment.",
  invalidEmail: "Enter a valid email or leave it blank.",
  tooLong: "Your comment exceeds the length limit.",
  loginFailed:
    "Sign-in could not be completed. You can still comment as a guest.",
  loginUnavailable:
    "Sign-in needs session storage. You can still comment as a guest.",
  comments: "comments",
  likesFailed: "Could not update the like. Please try again.",
};
const zh: typeof en = {
  heading: "评论",
  load: "查看评论",
  loading: "正在加载评论…",
  retry: "重试",
  refresh: "刷新评论",
  unavailable: "评论暂时无法加载，请稍后重试。",
  name: "称呼",
  email: "邮箱",
  optional: "选填",
  placeholder: "写评论…",
  send: "发表",
  sending: "正在发表…",
  login: "登录",
  logout: "退出",
  reply: "回复",
  replyTo: "回复",
  cancel: "取消回复",
  like: "赞",
  unlike: "取消赞",
  latest: "最新",
  oldest: "最早",
  hottest: "热门",
  sort: "评论排序",
  empty: "暂无评论",
  more: "查看更多",
  author: "作者",
  pinned: "置顶",
  pending: "等待审核",
  sent: "已发表",
  review: "留言已提交，审核后公开显示。",
  failed: "发表失败，输入的内容已保留。",
  unknown: "请求超时。留言可能已送达，请先刷新评论再决定是否重试。",
  required: "请填写称呼和留言内容。",
  invalidEmail: "请输入有效邮箱，或留空。",
  tooLong: "留言超过了字数限制。",
  loginFailed: "登录未完成，你仍可直接以访客身份留言。",
  loginUnavailable: "登录需要浏览器会话存储，你仍可直接以访客身份留言。",
  comments: "条评论",
  likesFailed: "点赞未成功，请重试。",
};
export function commentCopy(lang: string): typeof en {
  return lang.toLowerCase().startsWith("zh") ? zh : en;
}
export type CommentCopy = typeof en;
