"""Offline asset generation; Python + fontTools + brotli, none is a site dependency.

Usage: python scripts/refract-font-subset.py

Splits Refract's variable typeface into per-script files that the browser picks
by unicode-range. Every codepoint of the source stays available, with the slant
and weight axes intact; a Latin page simply stops downloading Cyrillic and
extended Latin outlines. The width axis keeps 100-125, the range the template
and its plugins use; the condensed widths below 100 stay in the source file.
Source: DINish (https://github.com/playbeing/dinish), SIL OFL 1.1, no Reserved Font Name.
"""
import hashlib
import io
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/components/refract/font/DINish-variable.woff2"
OUTPUT = ROOT / "public/templates/refract/fonts"
STYLES = ROOT / "src/components/refract/styles/typeface.css"

# The common "latin" range; everything else falls to Cyrillic or extended Latin.
LATIN = set(
    list(range(0x0000, 0x0100))
    + [0x0131, 0x0152, 0x0153, 0x02BB, 0x02BC, 0x02C6, 0x02DA, 0x02DC]
    + list(range(0x2000, 0x2070))
    + [0x20AC, 0x2122, 0x2191, 0x2193, 0x2212, 0x2215, 0xFEFF, 0xFFFD]
)
CYRILLIC = set(list(range(0x0400, 0x0530)) + [0x2116, 0x20B4])

codepoints = sorted(TTFont(SOURCE).getBestCmap())
latin = [c for c in codepoints if c in LATIN]
cyrillic = [c for c in codepoints if c in CYRILLIC]
extended = [c for c in codepoints if c not in LATIN and c not in CYRILLIC]
assert sorted(latin + cyrillic + extended) == codepoints

# Limit the width axis once, then reload it from bytes: the subsetter needs
# fully decoded tables, which a freshly instanced font does not have.
buffer = io.BytesIO()
instancer.instantiateVariableFont(TTFont(SOURCE), {"wdth": (100, 125)}).save(buffer)
limited = buffer.getvalue()


def unicode_range(points):
    spans, start, previous = [], points[0], points[0]
    for point in points[1:] + [None]:
        if point is not None and point == previous + 1:
            previous = point
            continue
        spans.append(f"U+{start:04X}" if start == previous else f"U+{start:04X}-{previous:04X}")
        if point is not None:
            start = previous = point
    return spans


def declaration(spans):
    """The project's formatted shape: one line when it fits, else wrapped at 80."""
    single = ", ".join(spans)
    if len(single) <= 61:
        return f"  unicode-range: {single};\n"
    lines, line = [], "   "
    for index, span in enumerate(spans):
        piece = f" {span}" + ("," if index + 1 < len(spans) else ";")
        if len(line) + len(piece) > 80:
            lines.append(line)
            line = "   "
        line += piece
    lines.append(line)
    return "  unicode-range:\n" + "\n".join(lines) + "\n"


faces, record = [], []
for name, points in (("cyrillic", cyrillic), ("latin-ext", extended), ("latin", latin)):
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.notdef_outline = True
    font = TTFont(io.BytesIO(limited))
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=points)
    subsetter.subset(font)
    target = OUTPUT / f"dinish-{name}.woff2"
    font.flavor = "woff2"
    font.save(target)
    record.append(
        dict(
            file=f"public/templates/refract/fonts/{target.name}",
            codepoints=len(points),
            bytes=target.stat().st_size,
            sha256=hashlib.sha256(target.read_bytes()).hexdigest(),
        )
    )
    faces.append(
        "@font-face {\n"
        "  font-family: RefractDIN;\n"
        f'  src: url("/templates/refract/fonts/{target.name}") format("woff2");\n'
        "  font-weight: 100 900;\n"
        "  font-style: oblique 0deg 12deg;\n"
        "  font-stretch: 100% 125%;\n"
        "  font-display: swap;\n" + declaration(unicode_range(points)) + "}\n"
    )

STYLES.write_text(
    "/* Generated by scripts/refract-font-subset.py. One typeface, split by script so a\n"
    "   page downloads only the outlines its text uses. */\n" + "".join(faces),
    encoding="utf8",
    newline="\n",
)
credit = dict(
    title="RefractDIN (DINish) per-script subsets",
    source="https://github.com/playbeing/dinish",
    license="SIL Open Font License 1.1",
    licenseFile="public/templates/refract/fonts/DINish-OFL.txt",
    sourceFile="src/components/refract/font/DINish-variable.woff2",
    sourceSha256=hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
    method="fontTools: width axis limited to 100-125, then subset by unicode-range; all layout features, names and the slnt and wght axes kept.",
    generator="scripts/refract-font-subset.py",
    outputs=record,
)
(ROOT / "public/templates/refract/font-credit.json").write_text(
    json.dumps(credit, indent=2) + "\n", encoding="utf8", newline="\n"
)
print(json.dumps([{r["file"].split("/")[-1]: r["bytes"]} for r in record]))
