import { resolveChromePath } from "./chrome.mjs";
import { chromium } from "playwright-core";
import fs from "node:fs/promises";

const base=process.env.BASE_URL || "http://127.0.0.1:4181";
const chrome = resolveChromePath();
const browser=await chromium.launch({executablePath:chrome,headless:true,args:["--use-fake-device-for-media-stream","--use-fake-ui-for-media-stream"]});
const results=[];
async function test(name,fn){try{const detail=await fn();results.push({name,ok:true,detail});console.log(`PASS ${name}${detail!==undefined?` :: ${JSON.stringify(detail)}`:""}`)}catch(error){results.push({name,ok:false,error:String(error)});console.log(`FAIL ${name} :: ${error}`)}}
const assert=(value,message)=>{if(!value)throw new Error(message)};

const desktop=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
await desktop.grantPermissions(["camera"],{origin:base});
const page=await desktop.newPage();
const localBad=[]; const consoleErrors=[];
page.on("response",r=>{if(r.url().startsWith(base)&&r.status()>=400)localBad.push({url:r.url(),status:r.status()})});
page.on("console",m=>{if(m.type()==="error")consoleErrors.push(m.text())});
await page.goto(base,{waitUntil:"domcontentloaded"});await page.waitForTimeout(700);

await test("hero greeting cycles",async()=>{const first=(await page.locator(".hero-greeting").innerText()).trim();await page.waitForFunction((value)=>document.querySelector(".hero-greeting")?.textContent?.trim()!==value,first,{timeout:5000});const second=(await page.locator(".hero-greeting").innerText()).trim();assert(first!==second,`greeting did not change: ${first}`);return {first,second}});
await test("portrait cycles on click",async()=>{const card=page.locator(".card-polaroid");const img=card.locator("img.polaroid-photo-image");const first=await img.getAttribute("src");await card.click();await page.waitForFunction((value)=>document.querySelector("img.polaroid-photo-image")?.getAttribute("src")!==value,first,{timeout:5000});const second=await card.locator("img.polaroid-photo-image").last().getAttribute("src");assert(first!==second,"portrait source did not change");return {first,second}});
await test("nav smooth-scroll About",async()=>{await page.locator('.nav-links a[href="#about"]').click();await page.waitForFunction(()=>scrollY>700,undefined,{timeout:5000});const y=await page.evaluate(()=>scrollY);return {scrollY:Math.round(y)}});
await test("About TLDR and Timeline switch",async()=>{const root=page.locator("#about");const tldr=root.locator("button:visible").filter({hasText:"TL;DR"}).first();await tldr.click();await page.waitForTimeout(350);assert(await root.locator(".profile-about-content.is-tldr").count()>0,"TLDR mode not applied");const timeline=root.locator("button:visible").filter({hasText:"Timeline"}).first();await timeline.click();await page.waitForTimeout(350);assert(await root.getByText("First smartphone").count()>0,"timeline content missing");return true});
await test("resume printer reaches ready and downloads PDF",async()=>{await page.evaluate(()=>scrollTo(0,0));const button=page.locator("button.resume-print-button");await button.click();const downloadButton=page.locator("button.resume-download-button");await downloadButton.waitFor({state:"visible",timeout:7000});const [download]=await Promise.all([page.waitForEvent("download",{timeout:5000}),downloadButton.click()]);const name=download.suggestedFilename();assert(name.toLowerCase().endsWith(".pdf"),`unexpected file ${name}`);return {filename:name}});
await test("camera starts, captures, and exposes Retake/Download",async()=>{const lens=page.locator('[role="button"][aria-label="Start camera"]');await lens.scrollIntoViewIfNeeded();await lens.click();await page.waitForFunction(()=>{const v=document.querySelector("video.lens-media");return v&&v.readyState>=2},{timeout:8000});const shutter=page.locator("button.shutter");assert(await shutter.isEnabled(),"shutter not enabled");await shutter.click();const retake=page.getByRole("button",{name:"Retake"});await retake.waitFor({state:"visible",timeout:6000});const dl=page.getByRole("button",{name:/Download/});await dl.waitFor({state:"visible",timeout:2000});return true});
await test("NotchShelf carousel controls",async()=>{const carousel=page.locator(".notchshelf-carousel");await carousel.scrollIntoViewIfNeeded();await carousel.hover();await page.waitForTimeout(500);const images=carousel.locator("img.notchshelf-carousel-image");const first=await images.last().getAttribute("src");await carousel.locator('button[aria-label="Next image"]').click();await page.waitForFunction((value)=>document.querySelector(".notchshelf-carousel img.notchshelf-carousel-image:last-of-type")?.getAttribute("src")!==value,first,{timeout:3000});const second=await images.last().getAttribute("src");assert(first!==second,"carousel did not advance");assert(await carousel.locator(".notchshelf-carousel-dot").count()===5,"expected 5 dots");return {first,second}});
await test("photography cards reveal all loaded images",async()=>{const section=page.locator("#photography");await section.scrollIntoViewIfNeeded();await page.waitForFunction(()=>{const cards=[...document.querySelectorAll("#photography .captures-grid > div")];return cards.length===18&&cards.every(card=>{const img=card.querySelector("img");return img&&img.complete&&img.naturalWidth>0&&Number(getComputedStyle(img).opacity)>=.99})&&!document.querySelector("#photography .skeleton-loader")},undefined,{timeout:7000});const state=await section.evaluate((root)=>{const cards=[...root.querySelectorAll(".captures-grid > div")];const visible=cards.filter(card=>{const img=card.querySelector("img");return img&&img.complete&&img.naturalWidth>0&&Number(getComputedStyle(img).opacity)>=.99}).length;return{cards:cards.length,visible,skeletons:root.querySelectorAll(".skeleton-loader").length}});assert(state.cards===18,`photo cards ${state.cards}`);assert(state.visible===18,`visible photos ${state.visible}/18`);assert(state.skeletons===0,`stale skeletons ${state.skeletons}`);return state});
await test("photography lightbox keyboard navigation and close",async()=>{const photo=page.locator("#photography .captures-grid").locator(":scope > div").first();await photo.scrollIntoViewIfNeeded();await photo.focus();await page.keyboard.press("Enter");const overlay=page.locator(".gallery-overlay");await overlay.waitFor({state:"visible",timeout:2000});const counter=overlay.locator("div").filter({hasText:/^\d+ \/ \d+$/}).last();const counter1=await counter.innerText();await page.keyboard.press("ArrowRight");await page.waitForFunction((value)=>[...document.querySelectorAll(".gallery-overlay div")].some(node=>/^\d+ \/ \d+$/.test(node.textContent?.trim()||"")&&node.textContent.trim()!==value),counter1,{timeout:3000});const counter2=await counter.innerText();assert(counter1!==counter2,"lightbox did not navigate");await page.keyboard.press("Escape");await overlay.waitFor({state:"detached",timeout:2000});return {counter1,counter2}});
await test("contact hover cycles style/text",async()=>{await page.evaluate(()=>scrollTo(0,0));const btn=page.locator(".nav .cycle-btn");const first=(await btn.innerText()).trim();await btn.hover();await page.waitForFunction((value)=>document.querySelector(".nav .cycle-btn")?.textContent?.trim()!==value,first,{timeout:3000});const second=(await btn.innerText()).trim();assert(first!==second,"contact button did not cycle");return {first,second}});
await test("offline screen appears and recovers",async()=>{await desktop.setOffline(true);try{await page.waitForTimeout(500);const offline=page.locator(".offline-screen");assert(await offline.isVisible(),"offline screen did not appear");assert((await offline.innerText()).includes("No internet connection"),"offline message mismatch");await desktop.setOffline(false);await page.waitForFunction(()=>!document.querySelector(".offline-screen"),{timeout:4000});assert(await offline.count()===0,"offline screen did not recover");return true}finally{await desktop.setOffline(false)}});
await test("weather API responds",async()=>{const r=await desktop.request.get(base+"/api/weather");assert(r.ok(),`status ${r.status()}`);const j=await r.json();assert("weatherCode" in j&&"isDay" in j,"weather shape invalid");return j});
await test("podcast API resolves 8 feeds",async()=>{const r=await desktop.request.get(base+"/api/podcasts");assert(r.ok(),`status ${r.status()}`);const j=await r.json();assert(Array.isArray(j)&&j.length===8,`feed count ${j?.length}`);return {count:j.length,artwork:j.filter(x=>x.artwork).length}});

await test("Clipt blog switches all 3 perspectives",async()=>{const p=await desktop.newPage();await p.goto(base+"/blogs/clipt",{waitUntil:"domcontentloaded"});await p.getByRole("button",{name:/For Designers/}).click();await p.getByText("Designing for Trust").waitFor({state:"visible",timeout:2000});await p.getByRole("button",{name:/Explain Like I'm Five/}).click();await p.getByText("How It Works (Simply Put)").waitFor({state:"visible",timeout:2000});await p.getByRole("button",{name:"The Story"}).click();await p.getByText("My Tech Stack").waitFor({state:"visible",timeout:2000});await p.close();return true});
await test("District count-up reaches 22% and 18%",async()=>{const p=await desktop.newPage();await p.goto(base+"/district",{waitUntil:"domcontentloaded"});const metrics=p.locator(".case-study-main-content").getByText(/increase|discoverability/i);for(let i=0;i<await metrics.count();i++)await metrics.nth(i).scrollIntoViewIfNeeded();await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await p.waitForFunction(()=>{const text=document.querySelector(".case-study-main-content")?.textContent||"";return text.includes("22%")&&text.includes("18%")},undefined,{timeout:6000});const text=await p.locator(".case-study-main-content").innerText();assert(text.includes("22%"),"22% missing");assert(text.includes("18%"),"18% missing");await p.close();return true});

const mobile=await browser.newContext({viewport:{width:390,height:844}});const mp=await mobile.newPage();await mp.goto(base,{waitUntil:"domcontentloaded"});
await test("mobile menu opens and scrolls",async()=>{const toggle=mp.locator("button.mobile-menu-toggle");await toggle.click();assert(await mp.locator(".mobile-nav-overlay.open").count()===1,"overlay not open");const about=mp.locator(".mobile-nav-menu a",{hasText:"About"});await about.waitFor({state:"visible"});await about.evaluate((element)=>element.click());await mp.waitForFunction(()=>scrollY>700,undefined,{timeout:5000});return true});
await test("mobile uses Brink mobile work image",async()=>{const brink=mp.locator(".mobile-work-brink .work-image-container img");await brink.scrollIntoViewIfNeeded();const src=await brink.getAttribute("src");assert(src?.includes("brink-work-mobile.jpg"),`unexpected ${src}`);return src});
await test("mobile camera controls remain available",async()=>{const count=await mp.locator('[role="button"][aria-label="Start camera"]').count();assert(count===1,`camera lens count ${count}`);return true});

await test("no same-origin 4xx/5xx during core homepage interactions",async()=>{assert(localBad.length===0,JSON.stringify(localBad));return true});
await test("no browser console errors during core homepage interactions",async()=>{const relevant=consoleErrors.filter(x=>!x.includes("favicon")&&!x.includes("ERR_INTERNET_DISCONNECTED"));assert(relevant.length===0,JSON.stringify(relevant));return true});

await desktop.close();await mobile.close();await browser.close();
const failed=results.filter(r=>!r.ok);
const summary={total:results.length,passed:results.length-failed.length,failed:failed.length,failures:failed};
await fs.writeFile("qa/functionality-report.json",JSON.stringify({base,summary,results},null,2));
console.log("\nSUMMARY",JSON.stringify(summary,null,2));
process.exitCode=failed.length?1:0;
